/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QKART_SANITY_LOGIN;

import org.openqa.selenium.chrome.ChromeDriver;
import java.util.Scanner;

public class QkartSanity {

    public static String lastGeneratedUserName;

    public static ChromeDriver createDriver() {
        ChromeDriver driver;
        String driverLocation = "";
        System.setProperty("webdriver.chrome.driver", driverLocation);
        System.setProperty("webdriver.chrome.logfile", "chromedriver.log");
        System.setProperty("webdriver.chrome.verboseLogging", "true");
        driver = new ChromeDriver();
        return driver;
    }

    public static void logStatus(String type, String message, String status) {

        System.out.println(String.format("%s |  %s  |  %s | %s", String.valueOf(java.time.LocalDateTime.now()), type,
                message, status));
    }

    /*
     * Testcase01: Verify the functionality of Login button on the Home page
     */
    public static Boolean TestCase01(ChromeDriver driver) throws InterruptedException {
        Boolean status;
        logStatus("Start TestCase", "Test Case 1: Verify User Registration", "DONE");
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("End TestCase", "Test Case 1: Verify user Regsitration : ", status ? "PASS" : "FAIL");

            // Return False as the test case Fails
            return false;
        } else {
            logStatus("TestCase 1", "Test Case Pass. User Registration Pass", "PASS");
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;
        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        logStatus("Test Step", "User Perform Login: ", status ? "PASS" : "FAIL");
        if (!status) {
            logStatus("End TestCase", "Test Case 1: Verify user Regsitration : ", status ? "PASS" : "FAIL");
            return false;
        }
        Home home = new Home(driver);
        status = home.PerformLogout();
        logStatus("End TestCase", "Test Case 1: Verify user Regsitration : ", status ? "PASS" : "FAIL");
        return status;
    }

    /*
     * Verify that an existing user is not allowed to re-register on QKart
     */
    public static Boolean TestCase02(ChromeDriver driver) throws InterruptedException {
        Boolean status;
        logStatus("Start Testcase", "Test Case 2: Verify User Registration with an existing username ", "DONE");
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("Test Step", "User Registration : ", status ? "PASS" : "FAIL");
            logStatus("End TestCase", "Test Case 2: Verify user Regsitration : ", status ? "PASS" : "FAIL");
            return false;

        } else {
            lastGeneratedUserName = registration.lastGeneratedUsername;
        }
        registration.navigateToRegisterPage();
        status = registration.registerUser(lastGeneratedUserName, "abc@123", false);
        // If status is true , then registration succeeded , else registration has
        // failed. In this case registration failure means Success
        logStatus("End TestCase", "Test Case 2: Verify user Regsitration : ", status ? "FAIL" : "PASS");
        return !status;
    }

    public static void main(String[] args) throws InterruptedException {
        int totalTests = 2;
        int passedTests = 0;
        Boolean status;


        try {
            // Execute Test Case 1
            status = TestCase01(driver);
            if (status) {
                passedTests = passedTests + 1;
            }

            // Execute Test Case 2
            status = TestCase02(driver);
            if (status) {
                passedTests = passedTests + 1;
            }
        } catch (Exception e) {
            throw e;
        } finally {
            // quit Chrome Driver
            driver.quit();

            System.out.println(String.format("%s out of %s test cases Passed ", Integer.toString(passedTests),
                    Integer.toString(totalTests)));
        }

    }
}
